# Generated by Django 5.1.6 on 2025-02-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('temperature_unit', models.CharField(choices=[('C', 'Celsius'), ('K', 'Kelvin')], default='C', max_length=1)),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('seeing', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('moon_phase', models.CharField(choices=[('New Moon', 'New Moon'), ('Full Moon', 'Full Moon'), ('First Quarter', 'First Quarter'), ('Last Quarter', 'Last Quarter')], default='New Moon', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telescope_name', models.CharField(choices=[('TARA', 'TARA'), ('HCT', 'HCT'), ('VBT', 'VBT')], max_length=100)),
                ('observatory_name', models.CharField(choices=[('PRL Mount Abu Observatory', 'PRL Mount Abu Observatory'), ('IUCAA Girawali Observatory', 'IUCAA Girawali Observatory')], max_length=100)),
                ('operator_name', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=50)),
                ('log_start_time', models.DateTimeField()),
                ('log_end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observing_mode', models.CharField(choices=[('Imaging', 'Imaging'), ('Spectroscopy', 'Spectroscopy')], default='Imaging', max_length=20)),
                ('instrument_name', models.CharField(max_length=100)),
                ('filter_in_use', models.CharField(choices=[('U', 'U'), ('B', 'B'), ('V', 'V'), ('R', 'R'), ('I', 'I')], default='U', max_length=10)),
                ('exposure_time', models.FloatField()),
                ('polarization_mode', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=100)),
                ('right_ascension', models.CharField(max_length=50)),
                ('declination', models.CharField(max_length=50)),
                ('air_mass', models.FloatField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_access', models.BooleanField(default=False)),
                ('remote_observer', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_stop', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelescopeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_type', models.CharField(choices=[('Alt-Azimuth', 'Alt-Azimuth'), ('Equatorial', 'Equatorial')], default='Alt-Azimuth', max_length=20)),
                ('pointing_accuracy', models.FloatField()),
                ('focus_position', models.FloatField()),
                ('tracking_mode', models.CharField(choices=[('Sidereal', 'Sidereal'), ('Lunar', 'Lunar'), ('Solar', 'Solar')], default='Sidereal', max_length=20)),
                ('guiding_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
    ]
