# Generated by Django 5.1.7 on 2025-04-27 13:04

import django.db.models.deletion
import logging_system.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telescope_name', models.CharField(choices=[('TARA (1.2meter)', 'TARA (1.2meter)'), ('BHARMA (2.5meter)', 'BHARMA (2.5meter)')], default='TARA (1.2meter)', max_length=100)),
                ('telescope_operator', models.CharField(max_length=100)),
                ('session_id', models.BigIntegerField(default=logging_system.models.generate_session_id, unique=True)),
                ('log_start_time_lst', models.DateTimeField(unique=True)),
                ('log_start_time_utc', models.DateTimeField()),
                ('log_end_time_lst', models.DateTimeField(unique=True)),
                ('log_end_time_utc', models.DateTimeField()),
                ('observer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('seeing', models.FloatField()),
                ('cloud_coverage', models.CharField(max_length=20)),
                ('moon_phase', models.CharField(choices=[('New Moon', 'New Moon'), ('Full Moon', 'Full Moon'), ('First Quarter', 'First Quarter'), ('Last Quarter', 'Last Quarter')], default='New Moon', max_length=20)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_condition', to='logging_system.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='logging_system.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observing_mode', models.CharField(choices=[('Imaging', 'Imaging'), ('Spectroscopy', 'Spectroscopy'), ('Spectropolarimetry', 'Spectropolarimetry'), ('Polarimetry', 'Polarimetry')], default='Imaging', max_length=20)),
                ('instrument_name', models.CharField(choices=[('PARAS-1', 'PARAS-1'), ('PARAS-2', 'PARAS-2'), ('ProtoPol', 'ProtoPol'), ('LISA', 'LISA'), ('EMPOL', 'EMPOL'), ('LRS', 'LRS'), ('FOSC', 'FOSC')], default='PARAS-1', max_length=100)),
                ('calibration', models.CharField(choices=[('Bias', 'Bias'), ('Sky', 'Sky'), ('Dark', 'Dark'), ('Flat', 'Flat'), ('lamp', 'lamp'), ('Not Applicable', 'Not Applicable')], default='Bias', max_length=20)),
                ('filter_in_use', models.CharField(choices=[('None', 'None'), ('U', 'U'), ('B', 'B'), ('V', 'V'), ('R', 'R'), ('I', 'I'), ('Enter Manually', 'Enter Manually')], default='U')),
                ('exposure_time', models.FloatField(default='10')),
                ('polarization_mode', models.BooleanField(default=False)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentation', to='logging_system.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=100)),
                ('right_ascension', models.CharField(max_length=50)),
                ('declination', models.CharField(max_length=50)),
                ('magnitude', models.CharField(max_length=50)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='logging_system.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_access', models.BooleanField(default=False)),
                ('remote_observer', models.CharField(blank=True, max_length=100, null=True)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remote_operation', to='logging_system.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TelescopeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_position', models.FloatField()),
                ('air_mass', models.FloatField(default=0)),
                ('tracking_mode', models.CharField(choices=[('Sidereal', 'Sidereal'), ('Non-Sidreal', 'Non-Sidreal'), ('Lunar', 'Lunar')], default='Sidereal', max_length=20)),
                ('guiding_status', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive'), ('Disaled', 'Disabled')], default='Active', max_length=20)),
                ('emergency_stop', models.BooleanField(default=False)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telescope_configuration', to='logging_system.generalinfo')),
            ],
        ),
    ]
