# Generated by Django 5.1.6 on 2025-02-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telescope_name', models.CharField(choices=[('TARA (1.2mm)', 'TARA (1.2mm)'), ('BHARMA (2.5mm)', 'BHARMA (2.5mm)')], default='TARA (1.2mm)', max_length=100)),
                ('observatory_name', models.CharField(choices=[('PRL Mount Abu Observatory', 'PRL Mount Abu Observatory')], default='PRL Mount Abu Observatory', max_length=100)),
                ('operator_name', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('log_start_time_lst', models.DateTimeField(unique=True)),
                ('log_start_time_utc', models.DateTimeField()),
                ('log_end_time_lst', models.DateTimeField(unique=True)),
                ('log_end_time_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('seeing', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('moon_phase', models.CharField(choices=[('New Moon', 'New Moon'), ('Full Moon', 'Full Moon'), ('First Quarter', 'First Quarter'), ('Last Quarter', 'Last Quarter')], default='New Moon', max_length=20)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_condition', to='logging_system.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='logging_system.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observing_mode', models.CharField(choices=[('Imaging', 'Imaging'), ('Spectroscopy', 'Spectroscopy'), ('Spectropolarimetry', 'Spectropolarimetry'), ('Polarimetry', 'Polarimetry')], default='Imaging', max_length=20)),
                ('instrument_name', models.CharField(choices=[('PARAS-1', 'PARAS-1'), ('PARAS-2', 'PARAS-2'), ('ProtoPol', 'ProtoPol'), ('LISA', 'LISA'), ('EMPOL', 'EMPOL'), ('LRS', 'LRS'), ('FOSC', 'FOSC')], default='PARAS-1', max_length=100)),
                ('filter_in_use', models.CharField(choices=[('None', 'None'), ('U', 'U'), ('B', 'B'), ('V', 'V'), ('R', 'R'), ('I', 'I')], default='U', max_length=10)),
                ('exposure_time', models.FloatField(default='10')),
                ('polarization_mode', models.BooleanField(default=False)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentation', to='logging_system.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=100)),
                ('right_ascension', models.TimeField(max_length=50)),
                ('declination', models.CharField(max_length=50)),
                ('air_mass', models.FloatField()),
                ('magnitude', models.CharField(max_length=50)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='logging_system.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_access', models.BooleanField(default=False)),
                ('remote_observer', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_stop', models.BooleanField(default=False)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remote_operation', to='logging_system.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TelescopeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_position', models.FloatField()),
                ('tracking_mode', models.CharField(choices=[('Sidereal', 'Sidereal'), ('Lunar', 'Lunar'), ('Solar', 'Solar')], default='Sidereal', max_length=20)),
                ('guiding_status', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive'), ('Disaled', 'Disabled')], default='Active', max_length=20)),
                ('general_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telescope_configuration', to='logging_system.generalinfo')),
            ],
        ),
    ]
