# Generated by Django 5.1.6 on 2025-02-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='log_end_time',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='log_start_time',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='lst_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='ust_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
