# Generated by Django 5.1.6 on 2025-02-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0002_remove_generalinfo_log_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='generalinfo',
            old_name='ust_time',
            new_name='log_end_time',
        ),
        migrations.RemoveField(
            model_name='telescopeconfiguration',
            name='mount_type',
        ),
        migrations.RemoveField(
            model_name='telescopeconfiguration',
            name='pointing_accuracy',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='log_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='utc_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='observatory_name',
            field=models.CharField(choices=[('PRL Mount Abu Observatory', 'PRL Mount Abu Observatory')], max_length=100),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='telescope_name',
            field=models.CharField(choices=[('TARA (1.2mm)', 'TARA (1.2mm)'), ('BHARMA (2.5mm)', 'BHARMA (2.5mm)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instrumentation',
            name='observing_mode',
            field=models.CharField(choices=[('Imaging', 'Imaging'), ('Spectroscopy', 'Spectroscopy'), ('Spectropolarimetry', 'Spectropolarimetry'), ('Polarimetry', 'Polarimetry')], default='Imaging', max_length=20),
        ),
        migrations.AlterField(
            model_name='telescopeconfiguration',
            name='guiding_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive'), ('Disaled', 'Disabled')], default='Active', max_length=20),
        ),
    ]
