# Generated by Django 5.1.6 on 2025-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0002_generalinfo_observer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='operator_name',
            new_name='telescope_operator',
        ),
        migrations.RemoveField(
            model_name='environmentalcondition',
            name='cloud_cover',
        ),
        migrations.AddField(
            model_name='environmentalcondition',
            name='cloud_coverage',
            field=models.TextField(default='sunny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='calibration',
            field=models.CharField(choices=[('Bias', 'Bias'), ('Dark', 'Dark'), ('Flat', 'Flat'), ('lamp', 'lamp')], default='Bias', max_length=20),
        ),
    ]
