# Generated by Django 5.1.6 on 2025-03-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0003_rename_operator_name_generalinfo_telescope_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalcondition',
            name='cloud_coverage',
            field=models.CharField(max_length=20),
        ),
    ]
