# Generated by Django 5.1.6 on 2025-02-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0003_comments_rename_ust_time_generalinfo_log_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='lst_time',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='utc_time',
        ),
    ]
