# Generated by Django 5.1.6 on 2025-03-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0004_alter_environmentalcondition_cloud_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='right_ascension',
            field=models.CharField(max_length=50),
        ),
    ]
