# Generated by Django 5.1.6 on 2025-02-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0004_remove_generalinfo_lst_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='log_end_time',
            new_name='log_end_time_lst',
        ),
        migrations.RenameField(
            model_name='generalinfo',
            old_name='log_start_time',
            new_name='log_end_time_utc',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='log_start_time_lst',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='log_start_time_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
