# Generated by Django 5.1.6 on 2025-02-21 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0005_rename_log_end_time_generalinfo_log_end_time_lst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='general_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='logging_system.generalinfo'),
        ),
        migrations.AddField(
            model_name='environmentalcondition',
            name='general_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_condition', to='logging_system.generalinfo'),
        ),
        migrations.AddField(
            model_name='instrumentation',
            name='general_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrumentation', to='logging_system.generalinfo'),
        ),
        migrations.AddField(
            model_name='observation',
            name='general_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='logging_system.generalinfo'),
        ),
        migrations.AddField(
            model_name='remoteoperation',
            name='general_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_operation', to='logging_system.generalinfo'),
        ),
        migrations.AddField(
            model_name='telescopeconfiguration',
            name='general_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telescope_configuration', to='logging_system.generalinfo'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='log_end_time_lst',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='log_end_time_utc',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='log_start_time_lst',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='log_start_time_utc',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='observatory_name',
            field=models.CharField(choices=[('PRL Mount Abu Observatory', 'PRL Mount Abu Observatory')], default='PRL Mount Abu Observatory', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='session_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='telescope_name',
            field=models.CharField(choices=[('TARA (1.2mm)', 'TARA (1.2mm)'), ('BHARMA (2.5mm)', 'BHARMA (2.5mm)')], default='TARA (1.2mm)', max_length=100),
        ),
        migrations.AlterField(
            model_name='instrumentation',
            name='polarization_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='observation',
            name='magnitude',
            field=models.FloatField(blank=True),
        ),
    ]
