# Generated by Django 5.1.6 on 2025-04-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0005_alter_observation_right_ascension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='observatory_name',
        ),
    ]
