# Generated by Django 5.1.6 on 2025-04-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0006_remove_generalinfo_observatory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='air_mass',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='calibration',
        ),
        migrations.RemoveField(
            model_name='remoteoperation',
            name='emergency_stop',
        ),
        migrations.AddField(
            model_name='instrumentation',
            name='calibration',
            field=models.CharField(choices=[('Bias', 'Bias'), ('Dark', 'Dark'), ('Flat', 'Flat'), ('lamp', 'lamp')], default='Bias', max_length=20),
        ),
        migrations.AddField(
            model_name='telescopeconfiguration',
            name='air_mass',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='telescopeconfiguration',
            name='emergency_stop',
            field=models.BooleanField(default=False),
        ),
    ]
