# Generated by Django 5.1.6 on 2025-02-21 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0006_comments_general_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='general_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='logging_system.generalinfo'),
        ),
        migrations.AlterField(
            model_name='environmentalcondition',
            name='general_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_condition', to='logging_system.generalinfo'),
        ),
        migrations.AlterField(
            model_name='instrumentation',
            name='general_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentation', to='logging_system.generalinfo'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='general_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='logging_system.generalinfo'),
        ),
        migrations.AlterField(
            model_name='remoteoperation',
            name='general_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remote_operation', to='logging_system.generalinfo'),
        ),
        migrations.AlterField(
            model_name='telescopeconfiguration',
            name='general_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telescope_configuration', to='logging_system.generalinfo'),
        ),
    ]
