# Generated by Django 5.1.6 on 2025-02-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0007_alter_comments_general_info_and_more'),
    ]

    operations = [
    ]
