# Generated by Django 5.1.7 on 2025-04-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logging_system", "0007_remove_observation_air_mass_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinfo",
            name="session_id",
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
