# Generated by Django 5.1.6 on 2025-02-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0008_auto_20250221_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentation',
            name='exposure_time',
            field=models.FloatField(default='10'),
        ),
    ]
