# Generated by Django 5.1.7 on 2025-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0008_alter_generalinfo_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='session_id',
            field=models.IntegerField(unique=True),
        ),
    ]
