# Generated by Django 5.1.6 on 2025-02-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0009_alter_instrumentation_exposure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='log_end_time_lst',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='log_start_time_lst',
            field=models.DateTimeField(unique=True),
        ),
    ]
