# Generated by Django 5.1.6 on 2025-02-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0010_alter_generalinfo_log_end_time_lst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentation',
            name='instrument_name',
            field=models.CharField(choices=[('PARAS-1', 'PARAS-1'), ('PARAS-2', 'PARAS-2'), ('ProtoPol', 'ProtoPol'), ('LISA', 'LISA'), ('EMPOL', 'EMPOL'), ('LRS', 'LRS'), ('FOSC', 'FOSC')], default='PARAS-1', max_length=100),
        ),
    ]
