# Generated by Django 5.1.6 on 2025-02-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0011_alter_instrumentation_instrument_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalcondition',
            name='temperature_unit',
        ),
        migrations.AlterField(
            model_name='instrumentation',
            name='filter_in_use',
            field=models.CharField(choices=[('None', 'None'), ('U', 'U'), ('B', 'B'), ('V', 'V'), ('R', 'R'), ('I', 'I')], default='U', max_length=10),
        ),
    ]
