# Generated by Django 5.1.6 on 2025-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0012_remove_environmentalcondition_temperature_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='magnitude',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
