# Generated by Django 5.1.6 on 2025-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0013_alter_observation_magnitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='magnitude',
            field=models.CharField(max_length=50),
        ),
    ]
