# Generated by Django 5.1.6 on 2025-02-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_system', '0014_alter_observation_magnitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='right_ascension',
            field=models.TimeField(max_length=50),
        ),
    ]
